// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCeYgJgXjLCrBcSJaDk8OhC126Y0z17yFY',
    appId: '1:819239021431:web:a92371cd8413a6c9ae4f72',
    messagingSenderId: '819239021431',
    projectId: 'personal-security-system-ad7f6',
    authDomain: 'personal-security-system-ad7f6.firebaseapp.com',
    databaseURL: 'https://personal-security-system-ad7f6-default-rtdb.firebaseio.com',
    storageBucket: 'personal-security-system-ad7f6.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMESQgywjswPFrWxjU_CTMTIp45rYtKwY',
    appId: '1:819239021431:android:f0222b06187ba708ae4f72',
    messagingSenderId: '819239021431',
    projectId: 'personal-security-system-ad7f6',
    databaseURL: 'https://personal-security-system-ad7f6-default-rtdb.firebaseio.com',
    storageBucket: 'personal-security-system-ad7f6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKb5sAHy0PwUqwxz_B5wHTyoujsVeQfKs',
    appId: '1:819239021431:ios:0dc91d5cd75efef5ae4f72',
    messagingSenderId: '819239021431',
    projectId: 'personal-security-system-ad7f6',
    databaseURL: 'https://personal-security-system-ad7f6-default-rtdb.firebaseio.com',
    storageBucket: 'personal-security-system-ad7f6.firebasestorage.app',
    iosBundleId: 'com.example.safetyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAKb5sAHy0PwUqwxz_B5wHTyoujsVeQfKs',
    appId: '1:819239021431:ios:0dc91d5cd75efef5ae4f72',
    messagingSenderId: '819239021431',
    projectId: 'personal-security-system-ad7f6',
    databaseURL: 'https://personal-security-system-ad7f6-default-rtdb.firebaseio.com',
    storageBucket: 'personal-security-system-ad7f6.firebasestorage.app',
    iosBundleId: 'com.example.safetyApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCeYgJgXjLCrBcSJaDk8OhC126Y0z17yFY',
    appId: '1:819239021431:web:2369c856267c4b64ae4f72',
    messagingSenderId: '819239021431',
    projectId: 'personal-security-system-ad7f6',
    authDomain: 'personal-security-system-ad7f6.firebaseapp.com',
    databaseURL: 'https://personal-security-system-ad7f6-default-rtdb.firebaseio.com',
    storageBucket: 'personal-security-system-ad7f6.firebasestorage.app',
  );
}
