// lib/models/emergency_contact.dart
// ✅ CORRECTED VERSION - Fixed all field names

class EmergencyContact {
  final int id;
  final int userId;
  final String name;
  final String phoneNumber; // ✅ FIXED
  final String? email;
  final String? relationship; // ✅ FIXED
  final int priority;
  final bool isActive;
  final bool isAutoGenerated;
  final int? autoFromGuardianId;
  final String source;
  final int? guardianRelationshipId;
  final DateTime createdAt;
  final DateTime updatedAt;

  EmergencyContact({
    required this.id,
    required this.userId,
    required this.name,
    required this.phoneNumber,
    this.email,
    this.relationship,
    required this.priority,
    required this.isActive,
    required this.isAutoGenerated,
    this.autoFromGuardianId,
    required this.source,
    this.guardianRelationshipId,
    required this.createdAt,
    required this.updatedAt,
  });

  factory EmergencyContact.fromJson(Map<String, dynamic> json) {
    return EmergencyContact(
      id: json['id'] as int,
      userId: json['user_id'] as int,
      name: json['contact_name'] as String,

      // ✅ Read 'phone_number' from backend
      phoneNumber: json['phone_number'] as String? ?? '',

      email: json['contact_email'] as String?,

      // ✅ Read 'relationship' from backend
      relationship: json['relationship'] as String?,

      priority: json['priority'] as int? ?? 999,
      isActive: json['is_active'] as bool? ?? true,
      isAutoGenerated: json['is_auto_generated'] as bool? ?? false,
      autoFromGuardianId: json['auto_from_guardian_id'] as int?,
      source: json['source'] as String? ?? 'manual',
      guardianRelationshipId: json['guardian_relationship_id'] as int?,

      createdAt: json['created_at'] != null
          ? DateTime.parse(json['created_at'] as String)
          : DateTime.now(),
      updatedAt: json['updated_at'] != null
          ? DateTime.parse(json['updated_at'] as String)
          : DateTime.now(),
    );
  }

  Map<String, dynamic> toJson() {
    return {
      'id': id,
      'user_id': userId,
      'contact_name': name,
      'phone_number': phoneNumber, // ✅ Send 'phone_number' to backend
      'contact_email': email,
      'relationship': relationship, // ✅ Send 'relationship' to backend
      'priority': priority,
      'is_active': isActive,
      'is_auto_generated': isAutoGenerated,
      'auto_from_guardian_id': autoFromGuardianId,
      'source': source,
      'guardian_relationship_id': guardianRelationshipId,
      'created_at': createdAt.toIso8601String(),
      'updated_at': updatedAt.toIso8601String(),
    };
  }

  // Computed properties
  bool get isPrimary => priority == 1;
  bool get isGuardianContact => source == 'auto_guardian' || isAutoGenerated;
  bool get isManualContact => source == 'manual';
  bool get isPhoneContact => source == 'phone_contacts';

  String get relationshipDisplay {
    if (relationship == null || relationship!.isEmpty) {
      return 'Emergency Contact';
    }
    return relationship!;
  }

  EmergencyContact copyWith({
    int? id,
    int? userId,
    String? name,
    String? phoneNumber,
    String? email,
    String? relationship,
    int? priority,
    bool? isActive,
    bool? isAutoGenerated,
    int? autoFromGuardianId,
    String? source,
    int? guardianRelationshipId,
    DateTime? createdAt,
    DateTime? updatedAt,
  }) {
    return EmergencyContact(
      id: id ?? this.id,
      userId: userId ?? this.userId,
      name: name ?? this.name,
      phoneNumber: phoneNumber ?? this.phoneNumber,
      email: email ?? this.email,
      relationship: relationship ?? this.relationship,
      priority: priority ?? this.priority,
      isActive: isActive ?? this.isActive,
      isAutoGenerated: isAutoGenerated ?? this.isAutoGenerated,
      autoFromGuardianId: autoFromGuardianId ?? this.autoFromGuardianId,
      source: source ?? this.source,
      guardianRelationshipId:
          guardianRelationshipId ?? this.guardianRelationshipId,
      createdAt: createdAt ?? this.createdAt,
      updatedAt: updatedAt ?? this.updatedAt,
    );
  }

  @override
  String toString() {
    String auto = isAutoGenerated ? ' [AUTO]' : '';
    return 'EmergencyContact(id: $id, name: $name, phone: $phoneNumber$auto)';
  }
}

// ✅ Schema for creating emergency contact
class CreateEmergencyContact {
  final String name;
  final String phoneNumber;
  final String? email;
  final String? relationship;
  final int priority;
  final String source;
  final int? dependentId; // ✅ ADDED for dependent contacts

  CreateEmergencyContact({
    required this.name,
    required this.phoneNumber,
    this.email,
    this.relationship,
    this.priority = 999,
    this.source = 'manual',
    this.dependentId,
  });

  Map<String, dynamic> toJson() {
    final data = {
      'contact_name': name,
      'phone_number': phoneNumber,
      'contact_email': email,
      'relationship': relationship,
      'priority': priority,
      'source': source,
      'is_active': true,
    };

    // ✅ Add dependent_id if provided
    if (dependentId != null) {
      data['dependent_id'] = dependentId;
    }

    return data;
  }
}

// ✅ Schema for updating emergency contact
class UpdateEmergencyContact {
  final int id;
  final String? name;
  final String? phoneNumber;
  final String? email;
  final String? relationship;
  final int? priority;
  final bool? isActive;

  UpdateEmergencyContact({
    required this.id,
    this.name,
    this.phoneNumber,
    this.email,
    this.relationship,
    this.priority,
    this.isActive,
  });

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = {};

    if (name != null) data['contact_name'] = name;
    if (phoneNumber != null) data['phone_number'] = phoneNumber;
    if (email != null) data['contact_email'] = email;
    if (relationship != null) data['relationship'] = relationship;
    if (priority != null) data['priority'] = priority;
    if (isActive != null) data['is_active'] = isActive;

    return data;
  }
}
